#!/usr/bin/env coot
# python script for coot - generated by dimple
set_nomenclature_errors_on_read("ignore")
import inspect, os
this_file = inspect.getfile(inspect.currentframe())
this_dir = os.path.dirname(os.path.abspath(this_file))
molecule = read_pdb(os.path.join(this_dir, "4xhe.pdb"))
set_rotation_centre(-67.1, 13.36, 52.25)
set_zoom(30.)
set_view_quaternion(-0.261564, -0.384477, 0, 0.885303)
refl = os.path.join(this_dir, "4xhe.mtz")
map21 = make_and_draw_map(refl, "FWT", "PHWT", "", 0, 0)
map11 = make_and_draw_map(refl, "DELFWT", "PHDELWT", "", 0, 1)
