#!/usr/bin/env coot
# python script for coot - generated by dimple
set_nomenclature_errors_on_read("ignore")
import inspect, os
this_file = inspect.getfile(inspect.currentframe())
this_dir = os.path.dirname(os.path.abspath(this_file))
molecule = read_pdb(os.path.join(this_dir, "5ybo.pdb"))
set_rotation_centre(-11.42, 65.69, 5.78)
set_zoom(30.)
set_view_quaternion(0.676169, -0.187649, 0, 0.712449)
refl = os.path.join(this_dir, "5ybo.mtz")
map21 = make_and_draw_map(refl, "FWT", "PHWT", "", 0, 0)
map11 = make_and_draw_map(refl, "DELFWT", "PHDELWT", "", 0, 1)
