#!/usr/bin/env coot
# python script for coot - generated by dimple
set_nomenclature_errors_on_read("ignore")
import inspect, os
this_file = inspect.getfile(inspect.currentframe())
this_dir = os.path.dirname(os.path.abspath(this_file))
molecule = read_pdb(os.path.join(this_dir, "4bam.pdb"))
set_rotation_centre(15.95, -12.99, 22.25)
set_zoom(30.)
set_view_quaternion(0.611885, 0.160774, 0, 0.774434)
refl = os.path.join(this_dir, "4bam.mtz")
map21 = make_and_draw_map(refl, "FWT", "PHWT", "", 0, 0)
map11 = make_and_draw_map(refl, "DELFWT", "PHDELWT", "", 0, 1)
